/*
 * Problem: 389. Find the Difference
 * Link: https://leetcode.com/problems/find-the-difference/
 * Difficulty: Easy
 * 
 * Description:
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 * 
 * Thought Process:
 * Using XOR bitwise operation is incredibly efficient here. A number XORed with itself is 0,
 * and XOR is commutative and associative. Therefore, if we XOR all the characters in both
 * strings, all the characters that appear in duplicate (in both s and t) will cancel out
 * to 0, leaving only the single extra character that was added.
 * 
 * Time Complexity: O(N) where N is the length of the string t. We iterate over both strings.
 * Space Complexity: O(1) as we only use a single character variable to track the XOR result.
 */

#include <iostream>
#include <string>

using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        char r = 0;
        for (char c : s)
            r ^= c;
        for (char c : t)
            r ^= c;
        return r;
    }
};

// Local Testing
int main() {
    Solution solution;
    
    // Test Case 1
    string s1 = "abcd";
    string t1 = "abcde";
    cout << "Input: s = \"" << s1 << "\", t = \"" << t1 << "\"\n";
    cout << "Output: " << solution.findTheDifference(s1, t1) << " (Expected: e)\n\n";

    // Test Case 2
    string s2 = "";
    string t2 = "y";
    cout << "Input: s = \"" << s2 << "\", t = \"" << t2 << "\"\n";
    cout << "Output: " << solution.findTheDifference(s2, t2) << " (Expected: y)\n";

    return 0;
}